colour = input("What is the color of roses: ")
object = input("Which object color is blue: ")
person = input("who is your's fav celebrity: ")
print("roses are " + colour)
print(object + " is blue")
print("And I Love " + person)